apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: razorpay-api
  description: API used in the payments system
spec:
  type: openapi
  lifecycle: production
  owner: 55tech
  system: payments
  definition: |
    GET /api/v1/tickets

    Response [ {
      "id": "23nnj45k111",
      .
      .
      .
    }]
    ...
