apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-ui
  description: This is the UI built on react framework.
  tags:
    - js
    - react
  annotations:
    circleci.com/project-slug: github/sahil-gulati/55-backstage-demo
    github.com/project-slug: sahil-gulati/55-backstage-demo
    backstage.io/techdocs-ref: url:https://github.com/Sahil-Gulati/55-backstage-demo/tree/main/
spec:
  type: service
  lifecycle: production
  owner: 55tech
  system: payments
  dependsOn:
    - "resource:rabbitmq-resource"
    - "resource:aws-s3-resource"
  providesApis:
    - "razorpay-wrapper-api"
    - "ccvenue-wrapper-api"

