apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-ui
  description: This is the UI built on react framework.
  tags:
    - js
    - react
spec:
  type: service
  lifecycle: production
  owner: 55tech
  system: payments
  dependsOn:
    - "resource:rabbitmq-resource"
    - "resource:aws-s3-resource"
  providesApis:
    - "razorpay-wrapper-api"
    - "ccvenue-wrapper-api"
