version: '2.4'

services:
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: backstage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
